/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BookRouteImport } from './routes/book'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeknisiRouteImport } from './routes/_app.teknisi'
import { Route as AppStokRouteImport } from './routes/_app.stok'
import { Route as AppRiwayatRouteImport } from './routes/_app.riwayat'
import { Route as AppRatingRouteImport } from './routes/_app.rating'
import { Route as AppProfilRouteImport } from './routes/_app.profil'
import { Route as AppOrderanRouteImport } from './routes/_app.orderan'
import { Route as AppKeuanganRouteImport } from './routes/_app.keuangan'
import { Route as AppJadwalRouteImport } from './routes/_app.jadwal'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicIpaymuWebhookRouteImport } from './routes/api/public/ipaymu-webhook'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeknisiRoute = AppTeknisiRouteImport.update({
  id: '/teknisi',
  path: '/teknisi',
  getParentRoute: () => AppRoute,
} as any)
const AppStokRoute = AppStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => AppRoute,
} as any)
const AppRiwayatRoute = AppRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AppRoute,
} as any)
const AppRatingRoute = AppRatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderanRoute = AppOrderanRouteImport.update({
  id: '/orderan',
  path: '/orderan',
  getParentRoute: () => AppRoute,
} as any)
const AppKeuanganRoute = AppKeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => AppRoute,
} as any)
const AppJadwalRoute = AppJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIpaymuWebhookRoute = ApiPublicIpaymuWebhookRouteImport.update({
  id: '/api/public/ipaymu-webhook',
  path: '/api/public/ipaymu-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AppDashboardRoute
  '/jadwal': typeof AppJadwalRoute
  '/keuangan': typeof AppKeuanganRoute
  '/orderan': typeof AppOrderanRoute
  '/profil': typeof AppProfilRoute
  '/rating': typeof AppRatingRoute
  '/riwayat': typeof AppRiwayatRoute
  '/stok': typeof AppStokRoute
  '/teknisi': typeof AppTeknisiRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/ipaymu-webhook': typeof ApiPublicIpaymuWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AppDashboardRoute
  '/jadwal': typeof AppJadwalRoute
  '/keuangan': typeof AppKeuanganRoute
  '/orderan': typeof AppOrderanRoute
  '/profil': typeof AppProfilRoute
  '/rating': typeof AppRatingRoute
  '/riwayat': typeof AppRiwayatRoute
  '/stok': typeof AppStokRoute
  '/teknisi': typeof AppTeknisiRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/ipaymu-webhook': typeof ApiPublicIpaymuWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/book': typeof BookRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/jadwal': typeof AppJadwalRoute
  '/_app/keuangan': typeof AppKeuanganRoute
  '/_app/orderan': typeof AppOrderanRoute
  '/_app/profil': typeof AppProfilRoute
  '/_app/rating': typeof AppRatingRoute
  '/_app/riwayat': typeof AppRiwayatRoute
  '/_app/stok': typeof AppStokRoute
  '/_app/teknisi': typeof AppTeknisiRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/ipaymu-webhook': typeof ApiPublicIpaymuWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/faq'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/refund'
    | '/register'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/jadwal'
    | '/keuangan'
    | '/orderan'
    | '/profil'
    | '/rating'
    | '/riwayat'
    | '/stok'
    | '/teknisi'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/ipaymu-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/faq'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/refund'
    | '/register'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/jadwal'
    | '/keuangan'
    | '/orderan'
    | '/profil'
    | '/rating'
    | '/riwayat'
    | '/stok'
    | '/teknisi'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/ipaymu-webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/book'
    | '/faq'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/refund'
    | '/register'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/dashboard'
    | '/_app/jadwal'
    | '/_app/keuangan'
    | '/_app/orderan'
    | '/_app/profil'
    | '/_app/rating'
    | '/_app/riwayat'
    | '/_app/stok'
    | '/_app/teknisi'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/ipaymu-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BookRoute: typeof BookRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  RefundRoute: typeof RefundRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicIpaymuWebhookRoute: typeof ApiPublicIpaymuWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/teknisi': {
      id: '/_app/teknisi'
      path: '/teknisi'
      fullPath: '/teknisi'
      preLoaderRoute: typeof AppTeknisiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stok': {
      id: '/_app/stok'
      path: '/stok'
      fullPath: '/stok'
      preLoaderRoute: typeof AppStokRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/riwayat': {
      id: '/_app/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof AppRiwayatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rating': {
      id: '/_app/rating'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof AppRatingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orderan': {
      id: '/_app/orderan'
      path: '/orderan'
      fullPath: '/orderan'
      preLoaderRoute: typeof AppOrderanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keuangan': {
      id: '/_app/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof AppKeuanganRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jadwal': {
      id: '/_app/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof AppJadwalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ipaymu-webhook': {
      id: '/api/public/ipaymu-webhook'
      path: '/api/public/ipaymu-webhook'
      fullPath: '/api/public/ipaymu-webhook'
      preLoaderRoute: typeof ApiPublicIpaymuWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppJadwalRoute: typeof AppJadwalRoute
  AppKeuanganRoute: typeof AppKeuanganRoute
  AppOrderanRoute: typeof AppOrderanRoute
  AppProfilRoute: typeof AppProfilRoute
  AppRatingRoute: typeof AppRatingRoute
  AppRiwayatRoute: typeof AppRiwayatRoute
  AppStokRoute: typeof AppStokRoute
  AppTeknisiRoute: typeof AppTeknisiRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppJadwalRoute: AppJadwalRoute,
  AppKeuanganRoute: AppKeuanganRoute,
  AppOrderanRoute: AppOrderanRoute,
  AppProfilRoute: AppProfilRoute,
  AppRatingRoute: AppRatingRoute,
  AppRiwayatRoute: AppRiwayatRoute,
  AppStokRoute: AppStokRoute,
  AppTeknisiRoute: AppTeknisiRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BookRoute: BookRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  RefundRoute: RefundRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicIpaymuWebhookRoute: ApiPublicIpaymuWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
